# Import socket module 
import socket
import pickle

# Create a socket object
s = socket.socket()

# Define the port on which you want to connect
port = 1234

# connect to the server on local computer
s.connect(('127.0.0.1', port))

# get user input 1 - 100
temp = 0
while (temp < 1) or (temp > 100):
    n = input("Enter a integer between 1 - 100:")
    temp = int(n)
    if (temp < 1) or (temp > 100):
        print("Error: Wrong integer value.")

# sending data to server
array = [n, 'Client of Jerry']
data = pickle.dumps(array)
s.send(data)

# receive server
try:
    arr = s.recv(4096)
    a = pickle.loads(arr)

    print("Receipt")
    print("Server Name: " + a[2])
    print("User input: " + n)
    print("Random Number Generated by Server: " + a[0])
    print("Sum: " + a[1])

except socket.error:
    print("Error Occured.")


# close the connection
print("Connection closed.")
s.close()
